FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
COPY wheels /wheels
RUN if [ -d /wheels ]; \
    then pip install --no-index --find-links /wheels -r requirements.txt; \
    else pip install --no-cache-dir -r requirements.txt; \
    fi
COPY app ./app
ENV DATA_DIR=/data
ENV DB_FILE=/data/datasets.db
RUN mkdir -p "$DATA_DIR"
CMD ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8000"]
