version: '3.9'
services:
  api:
    build:
      context: ./data-agent
      dockerfile: Dockerfile.api
    environment:
      - DATA_DIR=/data
      - DB_FILE=/data/datasets.db
      - MAX_FILE_SIZE=5242880
      - ALLOWED_FILE_TYPES=csv,xlsx
    volumes:
      - data_files:/data
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
  proxy:
    image: nginx:alpine
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      - frontend
    ports:
      - "8080:80"
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
volumes:
  data_files:
  ollama_data:
