name: CI

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r data-agent/requirements.txt -r requirements-dev.txt

      - name: Ruff check
        run: ruff check .

      - name: Mypy
        run: mypy data-agent/app/core

      - name: PyTest
        env:
          PYTHONPATH: data-agent
        run: python -m pytest -q

      - name: Build Docker image
        run: docker build -t data-agent ./data-agent

  publish-image:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build image
        run: docker build -t ghcr.io/${{ github.repository }}/data-agent:${{ github.ref_name }} ./data-agent

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push ghcr.io/${{ github.repository }}/data-agent:${{ github.ref_name }}

